customer:
  resource: '../src/Customer/Adapter/Framework/Config/Routes'
  type: directory
  prefix: 'api/customer'

employee:
  resource: 'routes/employee.yaml'
  prefix: 'api/employee'

rental:
  resource: 'routes/rental.yaml'
  prefix: 'api/rental'