customer:
  resource: '../src/Customer/Adapter/Framework/Config/Routes'
  type: directory
  prefix: 'api/customer'

employee:
  resource: 'routes/employee.yaml'
  prefix: 'employee'

rent:
  resource: 'routes/rent.yaml'
  prefix: 'rent'