customer:
  resource: '../src/Customer/Infrastructure/config/routes'
  type: directory
  prefix: 'customer'

employee:
  resource: 'routes/employee.yaml'
  prefix: 'employee'

rent:
  resource: 'routes/rent.yaml'
  prefix: 'rent'