imports:
  - { resource: '../src/Customer/Infrastructure/config/services/customer.yaml' }
  - { resource: '../src/Employee/Infrastructure/config/services/employee.yaml' }
  - { resource: '../src/Rent/Infrastructure/config/services/rent.yaml' }

